title: Lemontron
email: james@lemontron.com
description: "Lemontron is a portable printer that packs down into a filament box."
baseurl: ""
url: "https://lemontron.com"
#github_username: jamesloper
youtube_username: lemontron
bluesky_username: lemontron.com
discord_link: https://discord.com/invite/gSjfn4rnrm
collections:
  bom:
    output: true
    permalink: /lemontron/bom/:path/
  guides:
    output: true
    permalink: /lemontron/:path/
plugins:
  - jekyll-feed
permalink: /news/:title


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
