title: Lemontron
email: james@lemontron.com
description: "Lemontron is a portable printer that packs down into a filament box."
baseurl: ""
url: "https://lemontron.com"
youtube_username: lemontron
bluesky_username: lemontron.com
discord_link: https://discord.com/invite/gSjfn4rnrm
collections:
  bom:
    output: true
    permalink: /lemontron/bom/:path
  guides:
    output: true
    permalink: /lemontron/:path
plugins:
  - jekyll-feed
permalink: /blog/:title